name: Deploy documentation

on:
  # Only run when pull request is closed and merged into develop
  pull_request:
    branches:
      - develop
    types:
      - closed
    # Do not run on push excpet on tags
  push:
    branches-ignore:
      - "**"
    tags:
      - "**"

jobs:
  doc:
    runs-on: [self-hosted, docker]

    steps:
      - uses: actions/checkout@v3

      - name: Deploy documentation in staging
        if: ${{ github.event.pull_request.merged == true && github.ref_name == 'develop' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "staging.yml"
          repo: Cosmian/public_documentation
          ref: "develop"
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy documentation in prod
        if: startsWith(github.ref, 'refs/tags')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "prod.yml"
          repo: Cosmian/public_documentation
          ref: "main"
          token: ${{ secrets.PAT_TOKEN }}
